Adds new performance metrics
aws/sagemaker-xgboost-container pull request #213
Opened 2021-08-25 19:31 UTC by vjain1299

This PR adds new metrics to xgboost

**Changes**

custom_metrics.py:
- Adds balanced accuracy
- Adds precision
- Adds recall

**Testing**
- Integration tests ran with custom image: 900597767885.dkr.ecr.us-west-2.amazonaws.com/sagemaker-xgboost:add-metrics-vkjain
- New metric emissions were logged

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-09-02 16:19 UTC, mabunday requested changes

2021-09-02 16:19 UTC, mabunday commented on src/sagemaker_xgboost_container/metrics/custom_metrics.py
> +def balanced_accuracy(preds, dtrain):
You can define a base function `compute_score(preds, dtrain) -> score` and then simplify all of these functions to just 

```python
def balanced_accuracy(preds, dtrain):
  return 'balanced_accuracy', compute_score(preds, dtrain)
```

2021-09-08 16:01 UTC, mabunday approved these changes

2021-09-08 16:01 UTC, mabunday commented
Hmm looks like checks failed for the container. Please check these before merging.

2021-09-08 16:04 UTC, vjain1299 commented
> Hmm looks like checks failed for the container. Please check these before merging.

Can you rerun the codebuild? This happened with the prior commit as well due to changes in the buildspecs and it succeeded upon rerunning. (I don't have permissions to kick off the rerun)

2021-09-08 17:26 UTC, merged